AR = ['/usr/bin/ar']
ARFLAGS = ['rcs']
BINDIR = '/usr/local/bin'
CC = ['/usr/bin/gcc']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('9', '3', '0')
CFLAGS = ['-std=gnu99', '-g', '-Os', '-Wall', '-Wextra', '-Wshadow', '-Wcast-align', '-Wwrite-strings', '-Wno-unused-parameter', '-Werror']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_cshlib = ['-fPIC']
COMPILER_CC = 'gcc'
CPPPATH_ST = '-I%s'
CSP_HAVE_LIBSOCKETCAN = 1
DEFINES = []
DEFINES_ST = '-D%s'
DEFINE_COMMENTS = {'GIT_REV': '', 'CSP_FREERTOS': '', 'CSP_POSIX': '', 'CSP_WINDOWS': '', 'CSP_MACOSX': '', 'CSP_HAVE_LIBSOCKETCAN': '', 'CSP_DEBUG': '', 'CSP_DEBUG_TIMESTAMP': '', 'CSP_USE_RDP': '', 'CSP_USE_RDP_FAST_CLOSE': '', 'CSP_USE_CRC32': '', 'CSP_USE_HMAC': '', 'CSP_USE_XTEA': '', 'CSP_USE_PROMISC': '', 'CSP_USE_QOS': '', 'CSP_USE_DEDUP': '', 'CSP_USE_EXTERNAL_DEBUG': '', 'CSP_LOG_LEVEL_DEBUG': '', 'CSP_LOG_LEVEL_INFO': '', 'CSP_LOG_LEVEL_WARN': '', 'CSP_LOG_LEVEL_ERROR': '', 'CSP_LITTLE_ENDIAN': '', 'CSP_BIG_ENDIAN': '', 'LIBCSP_VERSION': ''}
DEST_BINFMT = 'elf'
DEST_CPU = 'x86_64'
DEST_OS = 'linux'
ENABLE_EXAMPLES = True
FEATURES = ['c', 'cstlib']
FILES_CSP = ['src/*.c', 'src/external/**/*.c', 'src/transport/**/*.c', 'src/crypto/**/*.c', 'src/interfaces/**/*.c', 'src/arch/*.c', 'src/arch/freertos/**/*.c', 'src/rtable/csp_rtable.c', 'src/rtable/csp_rtable_static.c', 'src/drivers/can/can_socketcan.c']
INCLUDES_CSP = ['include', '']
LIBCSP_SHLIB = None
LIBDIR = '/usr/local/lib'
LIBPATH_ST = '-L%s'
LIBS = ['socketcan']
LIB_LIBSOCKETCAN = ['socketcan']
LIB_ST = '-l%s'
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINK_CC = ['/usr/bin/gcc']
OS = ['freertos']
PKGCONFIG = ['/usr/bin/pkg-config']
PREFIX = '/usr/local'
RPATH_ST = '-Wl,-rpath,%s'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
cfg_files = ['/home/gama/libcsp/build_freertos/include/csp/csp_autoconfig.h']
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.so'
cstlib_PATTERN = 'lib%s.a'
define_key = []
macbundle_PATTERN = '%s.bundle'
